TITLE Mod file for component: Component(id=expTwoSynapseAct type=expTwoSynapseAct)

COMMENT

    This NEURON file has been generated by org.neuroml.export (see https://github.com/NeuroML/org.neuroml.export)
         org.neuroml.export  v1.4.6
         org.neuroml.model   v1.4.6
         jLEMS               v0.9.8.6

ENDCOMMENT

NEURON {
    POINT_PROCESS expTwoSynapseAct
    RANGE tauRise                           : parameter
    RANGE tauDecay                          : parameter
    RANGE delay                             : parameter
    RANGE duration                          : parameter
    RANGE peakTime                          : parameter
    RANGE waveformFactor                    : parameter
    RANGE gbase                             : parameter
    RANGE erev                              : parameter
    
    RANGE g                                 : exposure
    
    RANGE i                                 : exposure
    
    
    NONSPECIFIC_CURRENT i 
    
}

UNITS {
    
    (nA) = (nanoamp)
    (uA) = (microamp)
    (mA) = (milliamp)
    (A) = (amp)
    (mV) = (millivolt)
    (mS) = (millisiemens)
    (uS) = (microsiemens)
    (molar) = (1/liter)
    (kHz) = (kilohertz)
    (mM) = (millimolar)
    (um) = (micrometer)
    (umol) = (micromole)
    (S) = (siemens)
    
}

PARAMETER {
    
    tauRise = 0.16 (ms)
    tauDecay = 1.8 (ms)
    delay = 150 (ms)
    duration = 10000 (ms)
    peakTime = 0.42504025 (ms)
    waveformFactor = 1.389889 
    gbase = 2.0E-5 (uS)
    erev = -75 (mV)
}

ASSIGNED {
    ? Standard Assigned variables with baseSynapse
    v (mV)
    celsius (degC)
    temperature (K)
    
    g (uS)                                 : derived variable
    
    i (nA)                                 : derived variable
    rate_A (/ms)
    rate_B (/ms)
    
}

STATE {
    active  
    A  
    B  
    
}

INITIAL {
    temperature = celsius + 273.15
    
    rates()
    rates() ? To ensure correct initialisation.
    
    A = 0
    
    B = 0
    
}

BREAKPOINT {
    
    SOLVE states METHOD cnexp
    
    if (t <  delay) {
        active = 0 ? standard OnCondition
    }
    
    if (t >=  delay  && t <  duration  +  delay) {
        active = 1 ? standard OnCondition
    }
    
    if (t >=  duration  +  delay) {
        active = 0 ? standard OnCondition
    }
    
    
}

NET_RECEIVE(weight) {
    ?state_discontinuity(A, A  + (  active   * weight *   waveformFactor  )) : From expTwoSynapseAct
    A = A  + (  active   * weight *   waveformFactor  ) : From expTwoSynapseAct
    ?state_discontinuity(B, B  + (  active   * weight *   waveformFactor  )) : From expTwoSynapseAct
    B = B  + (  active   * weight *   waveformFactor  ) : From expTwoSynapseAct
    
}

DERIVATIVE states {
    rates()
    A' = rate_A 
    B' = rate_B 
    
}

PROCEDURE rates() {
    
    g = gbase  * (  B   -   A  ) ? evaluable
    i = -1 * g  * (  erev   - v) ? evaluable
    rate_A = -  A   /  tauRise ? Note units of all quantities used here need to be consistent!
    rate_B = -  B   /  tauDecay ? Note units of all quantities used here need to be consistent!
    
     
    
}

